{
 "title": "Open Code Quest",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(acm_managed_cluster_labels,name)"
    }
   },
   {
    "name": "team",
    "label": "Team",
    "query": "team1, team2, team3, team4, team5, team6"
   }
  ]
 },
 "panels": [
  {
   "title": "Etat d'avancement de toutes les équipes - 3 clusters de 5 équipes (Total 15)",
   "type": "bargauge",
   "description": "Nombre d’équipes ayant terminé l’étape 'import des utilisateurs'",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max((count(catalog_entities_count{kind=\"user\", namespace=~\"rhdh-team[1-5]+\"} >= 35)) or on() vector(0))",
     "legendFormat": "__auto"
    },
    {
     "expr": "max((count(catalog_entities_count{kind=\"template\", namespace=~\"rhdh-team[1-5]+\"} >= 4))  or on() vector(0))",
     "legendFormat": "__auto"
    },
    {
     "expr": "max((count(catalog_entities_count{kind=\"component\", namespace=~\"rhdh-team[1-5]+\"} >= 4))  or on() vector(0))",
     "legendFormat": "__auto"
    },
    {
     "expr": "max((count(kube_pod_info{\n    namespace=~\"devteam[1-5]+-workshop-dev\",\n    pod=~\"hero-.*\",\n    pod!~\".*database.*\",\n    created_by_kind=\"ReplicaSet\"}) > 0) or on() vector(0))",
     "legendFormat": "__auto"
    },
    {
     "expr": "max((count(kube_pod_info{\n    namespace=~\"devteam[1-5]+-workshop-preprod\",\n    pod=~\"hero-.*\",\n    pod!~\".*database.*\",\n    created_by_kind=\"ReplicaSet\"}) > 0) or on() vector(0))",
     "legendFormat": "__auto"
    },
    {
     "expr": "max((count(kube_pod_info{\n    namespace=~\"devteam[1-5]+-workshop-prod\",\n    pod=~\"hero-.*\",\n    pod!~\".*database.*\",\n    created_by_kind=\"ReplicaSet\"}) > 0) or on() vector(0))",
     "legendFormat": "__auto"
    },
    {
     "expr": "max((count(kube_pod_info{\n    namespace=~\"devteam[1-5]+-workshop-dev\",\n    pod=~\"villain-.*\",\n    pod!~\".*database.*\",\n    created_by_kind=\"ReplicaSet\"}) > 0) or on() vector(0))",
     "legendFormat": "__auto"
    },
    {
     "expr": "max((count(kube_pod_info{\n    namespace=~\"devteam[1-5]+-workshop-preprod\",\n    pod=~\"villain-.*\",\n    pod!~\".*database.*\",\n    created_by_kind=\"ReplicaSet\"}) > 0) or on() vector(0))",
     "legendFormat": "__auto"
    },
    {
     "expr": "max((count(kube_pod_info{\n    namespace=~\"devteam[1-5]+-workshop-prod\",\n    pod=~\"villain-.*\",\n    pod!~\".*database.*\",\n    created_by_kind=\"ReplicaSet\"}) > 0) or on() vector(0))",
     "legendFormat": "__auto"
    },
    {
     "expr": "max((count(kube_pod_info{\n    namespace=~\"devteam[1-5]+-workshop-dev\",\n    pod=~\"fight-.*\",\n    pod!~\".*database.*|fight-ui.*\",\n    created_by_kind=\"ReplicaSet\"}) > 0) or on() vector(0))",
     "legendFormat": "__auto"
    },
    {
     "expr": "max((count(kube_pod_info{\n    namespace=~\"devteam[1-5]+-workshop-preprod\",\n    pod=~\"fight-.*\",\n    pod!~\".*database.*|fight-ui.*\",\n    created_by_kind=\"ReplicaSet\"}) > 0) or on() vector(0))",
     "legendFormat": "__auto"
    },
    {
     "expr": "max((count(kube_pod_info{\n    namespace=~\"devteam[1-5]+-workshop-prod\",\n    pod=~\"fight-.*\",\n    pod!~\".*database.*|fight-ui.*\",\n    created_by_kind=\"ReplicaSet\"}) > 0) or on() vector(0))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Progression des équipes dans le déploiement des entités RHDH - $cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Entité utilisateur",
     "type": "gauge",
     "description": "Nombre d’équipes ayant terminé l’étape 'import des utilisateurs'",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(catalog_entities_count{kind=\"user\", cluster=\"$cluster\", namespace=~\"rhdh-team[0-9]+\"} == 35)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Entité template",
     "type": "gauge",
     "description": "Nombre d’équipes ayant terminé l’étape 'import des templates'",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(catalog_entities_count{kind=\"template\", cluster=\"$cluster\", namespace=~\"rhdh-team[0-9]+\"} == 4)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Entités component",
     "type": "gauge",
     "description": "Nombre d’équipes ayant terminé l’étape 'import des components'",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(catalog_entities_count{kind=\"component\", cluster=\"$cluster\", namespace=~\"rhdh-team[0-9]+\"} == 4)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Métriques RHDH (rhdh-team)",
     "type": "table",
     "gridPos": { "h": 0, "w": 24, "x": 0, "y": 20 },
     "repeat": "cluster",
     "targets": [
      {
       "expr": "sum by (namespace) (kube_pod_owner{cluster=\"$cluster\", namespace=~\".*rhdh-team.*\"})",
       "legendFormat": "{{namespace}}"
      },
      {
       "expr": "max by (namespace) (catalog_entities_count{kind=\"user\", cluster=\"$cluster\", namespace=~\"rhdh-team.*\"})",
       "legendFormat": "{{namespace}}"
      },
      {
       "expr": "max by (namespace) (catalog_entities_count{kind=\"template\", cluster=\"$cluster\", namespace=~\"rhdh-team.*\"})",
       "legendFormat": "{{namespace}}"
      },
      {
       "expr": "max by (namespace) (catalog_entities_count{kind=\"component\", cluster=\"$cluster\", namespace=~\"rhdh-team.*\"})",
       "legendFormat": "{{namespace}}"
      }
     ]
    }
   ]
  },
  {
   "title": "État des déploiements $team - $cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "repeat": "team"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 14 },
   "options": {
    "content": "<p style=\"text-align: center; padding-top: 1em; text-transform: capitalize;\">\n  ${team}\n</p>"
   }
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_info{\n    cluster= \"$cluster\",\n    namespace=~\"dev$team-workshop-dev\",\n    pod=~\"hero-.*\",\n    pod!~\".*database.*\",\n    created_by_kind=\"ReplicaSet\"}) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_info{\n    cluster= \"$cluster\",\n    namespace=~\"dev$team-workshop-preprod\",\n    pod=~\"hero-.*\",\n    pod!~\".*database.*\",\n    created_by_kind=\"ReplicaSet\"}) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_info{\n    cluster= \"$cluster\",\n    namespace=~\"dev$team-workshop-prod\",\n    pod=~\"hero-.*\",\n    pod!~\".*database.*\",\n    created_by_kind=\"ReplicaSet\"}) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_info{\n    cluster= \"$cluster\",\n    namespace=~\"dev$team-workshop-dev\",\n    pod=~\"villain-.*\",\n    pod!~\".*database.*\",\n    created_by_kind=\"ReplicaSet\"}) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_info{\n    cluster= \"$cluster\",\n    namespace=~\"dev$team-workshop-preprod\",\n    pod=~\"villain-.*\",\n    pod!~\".*database.*\",\n    created_by_kind=\"ReplicaSet\"}) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_info{\n    cluster= \"$cluster\",\n    namespace=~\"dev$team-workshop-prod\",\n    pod=~\"villain-.*\",\n    pod!~\".*database.*\",\n    created_by_kind=\"ReplicaSet\"}) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_info{\n    cluster= \"$cluster\",\n    namespace=~\"dev$team-workshop-dev\",\n    pod=~\"fight-.*\",\n    pod!~\".*database.*|fight-ui.*\",\n    created_by_kind=\"ReplicaSet\"}) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_info{\n    cluster= \"$cluster\",\n    namespace=~\"dev$team-workshop-preprod\",\n    pod=~\"fight-.*\",\n    pod!~\".*database.*|fight-ui.*\",\n    created_by_kind=\"ReplicaSet\"}) > 0 ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_info{\n    cluster= \"$cluster\",\n    namespace=~\"dev$team-workshop-prod\",\n    pod=~\"fight-.*\",\n    pod!~\".*database.*|fight-ui.*\",\n    created_by_kind=\"ReplicaSet\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Suivi détaillé du déploiement des entités RHDH - $cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 }
  },
  {
   "title": "Métriques RHDH (rhdh-team)",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
   "repeat": "cluster",
   "targets": [
    {
     "expr": "sum by (namespace) (kube_pod_owner{cluster=\"$cluster\", namespace=~\"rhdh-team.*\"})",
     "legendFormat": "{{namespace}}"
    },
    {
     "expr": "max by (namespace) (catalog_entities_count{kind=\"user\", cluster=\"$cluster\", namespace=~\"rhdh-team.*\"})",
     "legendFormat": "{{namespace}}"
    },
    {
     "expr": "max by (namespace) (catalog_entities_count{kind=\"template\", cluster=\"$cluster\", namespace=~\"rhdh-team.*\"})",
     "legendFormat": "{{namespace}}"
    },
    {
     "expr": "max by (namespace) (catalog_entities_count{kind=\"component\", cluster=\"$cluster\", namespace=~\"rhdh-team.*\"})",
     "legendFormat": "{{namespace}}"
    }
   ]
  }
 ]
}