apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: open-code-quest-config
placementBindingDefaults:
  name: open-code-quest-binding
policyDefaults:
  remediationAction: enforce
  severity: high
  namespace: observability
  placement:
      labelSelector:
        matchLabels:
          local-cluster: "true"
policies:
  - name: open-code-quest
    manifests:
      - path: observability-metrics-custom-allowlist-cm.yaml
      - path: open-code-quest-custom-dashboard.yaml

