{
 "title": "Open Code Quest",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(acm_managed_cluster_labels,name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Utilisation CPU ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "1 - avg by(cluster) (rate(node_cpu_seconds_total{mode=\"idle\", cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Utilisation mémoire",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "1- (sum by (cluster)(\n  :node_memory_MemAvailable_bytes:sum{cluster=\"$cluster\"}\n)\n/\nsum by (cluster)(\n  kube_node_status_allocatable{cluster=\"$cluster\" , resource=\"memory\"}\n))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Métriques RHDH (rhdh-team)",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "sum by (namespace) (kube_pod_owner{cluster=\"$cluster\", namespace=~\".*rhdh-team.*\"})",
     "legendFormat": "{{namespace}}"
    },
    {
     "expr": "max by (namespace) (catalog_entities_count{kind=\"user\", cluster=\"$cluster\", namespace=~\"rhdh-team.*\"})",
     "legendFormat": "{{namespace}}"
    },
    {
     "expr": "max by (namespace) (catalog_entities_count{kind=\"template\", cluster=\"$cluster\", namespace=~\"rhdh-team.*\"})",
     "legendFormat": "{{namespace}}"
    },
    {
     "expr": "max by (namespace) (catalog_entities_count{kind=\"component\", cluster=\"$cluster\", namespace=~\"rhdh-team.*\"})",
     "legendFormat": "{{namespace}}"
    }
   ]
  }
 ]
}